---
   - name: Download filebeat 
     shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.16.2-amd64.deb

   - name: Installation filebeat
     shell: dpkg -i filebeat-7.16.2-amd64.deb

   - name: Copy filebeat config file
     template:
       src: filebeat.j2
       dest: /etc/filebeat/filebeat.yml

   - name: Copy filebeat-reference file
     template:
       src: filebeat.reference.j2
       dest: /etc/filebeat/filebeat.reference.yml

   - name: Start filebeat
     shell: systemctl start filebeat
