- hosts: all
  gather_facts: yes
  tasks:
 
    - name: Adding new VPN user
      shell: /scripts/ExpectAddUserVPN {{ name }} {{ openvpn_master_password }}
      args:
        chdir: /users

    - name: Copying .ovpn file to current pc 'ovpn_users' directory
      fetch:
        src: /users/{{ name }}.ovpn
        dest: /ovpn_users/{{ name }}.ovpn
        flat: yes
