---
   - name: Include configuration vars
     include_vars:
       file: ./ELK_configuration.yml

   - name: Pulling docker logstash image
     shell: docker pull logstash:7.16.2

   - name: Copy install_logstash script
     copy:
       src: install_logstash
       dest: ~/install_logstash
       mode: "0700"

   - name: Copy config file
     template:
       src: logstash.j2
       dest: ~/logstash.yml

   - name: Copy logstash-sample.yml file
     template:
       src: logstash-sample.j2
       dest: ~/logstash-sample.conf

   - name: Create pipeline dir
     file:
       state: directory
       path: ~/pipeline

   - name: Execute install_logstash
     shell: ~/install_logstash

