- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Create user bot   
      user:
        name: bot
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/bot_rsa
        state: present
        shell: /bin/bash
        force: no

    - name: Get name of current user
      shell: pwd | tr "/" "\n"
      register: output   

    - name: Copy public key to current directory
      shell: cp /home/bot/.ssh/bot_rsa.pub ./bot_rsa.pub

    - name: Copy private key to current directory
      shell: cp /home/bot/.ssh/bot_rsa ./bot_rsa

    - name: Change owner of keys
      shell: chown {{ output.stdout_lines[2] }}:{{ output.stdout_lines[2] }} ./bot_rsa ./bot_rsa.pub
