- hosts: elastic_server, kibana_server, logstash_server
  become: yes
  roles:
    - { role: ServerDocker }

- hosts: elastic_server
  become: yes
  remote_user: bot
  roles:
    - { role: ElasticServer }

- hosts: kibana_server
  become: yes
  remote_user: bot
  roles:
    - { role: KibanaServer }

- hosts: logstash_server
  become: yes
  remote_user: bot
  roles:
    - { role: LogStashServer }


