---

    - name: Get cadvisor docker container name
      shell: docker ps -a | grep "/usr/bin/cadvisor" | awk '{ print $NF }'
      register: image_name

    - name: Killing container
      shell: docker kill {{ image_name.stdout }}
      ignore_errors: True
      when: image_name.stdout != ""

    - name: Removing container
      shell: docker rm {{ image_name.stdout }}
      when: image_name.stdout != ""

    - name: Create directory if not exists
      file:
        path: ~/scripts
        state: directory

    - name: Copy SetupcAdvisor script
      template:
        src: SetupcAdvisor.j2
        dest: ~/scripts/SetupcAdvisor
        mode: "0777"

    - name: Execute SetupcAdvisor script
      shell: ~/scripts/SetupcAdvisor

    - name: Remove scripts dir
      shell: rm -r -f ~/scripts
