---
    - name: Including check working containers
      include_role:
        name: ServerDocker
        tasks_from: manage_copy_images
      vars:
        container_name: "/usr/bin/cadvisor"

    - name: Create directory if not exists
      file:
        path: ~/scripts
        state: directory

    - name: Copy SetupcAdvisor script
      template:
        src: SetupcAdvisor.j2
        dest: ~/scripts/SetupcAdvisor
        mode: "0777"

    - name: Execute SetupcAdvisor script
      shell: ~/scripts/SetupcAdvisor {{ subnet.stdout }}

    - name: Remove scripts dir
      shell: rm -r -f ~/scripts
