---
    - name: Create directory in ~/ for OS images source files
      file:
        path: ~/sourceFiles
        state: directory

    - name: Copy necessary resources for building OS images
      copy:
        src: ./images
        dest: ~/sourceFiles/
        mode: "0777"

    - name: Building XFCE version of OS
      shell: ./buildContainer.sh xfce
      args:
        chdir: ~/sourceFiles/images/

    - name: Building ICEWM version of OS
      shell: ~/sourceFiles/images/buildContainer.sh icewm

    - name: Installing OpenVPN client
      apt:
        pkg:
          - openvpn
        state: present

    - name: Copying createWorkstation script to /usr/local/bin
      copy:
        src: ./serverScripts/createWorkstation
        dest: /usr/local/bin/
        mode: "0777"

    - name: Copying destroyWorkstation script to /usr/local/bin
      copy:
        src: ./serverScripts/destroyWorkstation
        dest: /usr/local/bin/
        mode: "0777"

    - name: Copying .ovpn file to /etc/openvpn/server
      copy:
        src: ovpn_users/server.ovpn
        dest: /etc/openvpn/server/server.conf

    - name: Start openvpn server
      shell: systemctl start openvpn-server@server

    - name: Install_cadvisor.yml
      import_tasks: install_cadvisor.yml
      when: cadvisor_enabled == "true"

    - name: Install filebeat
      import_tasks: filebeat.yml
      when: filebeat_enabled == "true"
