---
    - name: Include configuration vars
      include_vars:
        file: ./variables.yml

    - name: Create directory in ~/ for OS images source files
      file:
        path: ~/sourceFiles
        state: directory

    - name: Copy necessary resources for building OS images
      copy:
        src: ./images
        dest: ~/sourceFiles/
        mode: "0777"

    - name: Building XFCE version of OS
      shell: ./buildContainer.sh xfce
      args:
        chdir: ~/sourceFiles/images/

    - name: Building ICEWM version of OS
      shell: ~/sourceFiles/images/buildContainer.sh icewm

    - name: Copying createWorkstation script to /usr/local/bin
      copy:
        src: ./serverScripts/createWorkstation
        dest: /usr/local/bin/
        mode: "0777"

    - name: Copying destroyWorkstation script to /usr/local/bin
      copy:
        src: ./serverScripts/destroyWorkstation
        dest: /usr/local/bin/
        mode: "0777"

    - name: Including role OpenVPN
      include_role:
        name: OpenVPN
      vars:
        server_name: "server"

    - name: Identifying vpn network
      shell: ip address | grep tun0 -A2 | grep "inet " | awk '{print $2}'
      register: subnet

    - name: Adding COREIP var to local /etc/environment
      shell: sed -i -e '/export COREIP=/d' /etc/environment && echo "export COREIP=\"{{ subnet.stdout }}\"" >> /etc/environment
      delegate_to: 127.0.0.1

    - name: Install_cadvisor.yml
      import_tasks: install_cadvisor.yml
      when: cadvisor_enabled == "true"

    - name: Install filebeat
      import_tasks: filebeat.yml
      when: filebeat_enabled == "true"
