---

   - name: Get ovpn docker container name
     shell: docker ps -a | grep "ovpn_run" | awk '{ print $NF }'
     register: image_name

   - name: Killing container
     shell: docker kill {{ image_name.stdout }}
     ignore_errors: True
     when: image_name.stdout != ""

   - name: Removing container
     shell: docker rm {{ image_name.stdout }}
     when: image_name.stdout != ""

   - name: Include configuration vars
     include_vars:
       file: ./variables.yml

   - name: Install base utils
     become: yes
     apt:
       pkg:
         - expect
         - curl
         - dnsutils
       state: present
       update_cache: yes

   - name: Create folder for scripts
     file:
       state: directory
       path: ~/scripts

   - name: Create folder for users
     file:
       state: directory
       path: ~/users

   - name: Copy SetupVPN script
     copy:
       src: server_scripts/setupVPN.sh
       dest: ~/scripts/setupVPN.sh
       mode: "0700"

   - name: Copy AddVPNUser script
     copy:
       src: server_scripts/addVPNUser.sh
       dest: ~/scripts/addVPNUser.sh
       mode: "0700"

   - name: Copy expect script ExpectSetupVPN
     copy:
       src: expect_scripts/ExpectSetupVPN
       dest: ~/scripts/ExpectSetupVPN
       mode: "0700"

   - name: Copy expect script ExpectAddUserVPN
     copy:
       src: expect_scripts/ExpectAddUserVPN
       dest: ~/scripts/ExpectAddUserVPN
       mode: "0700"

   - name: Copy ExpectDeleteUser script
     copy:
       src: expect_scripts/ExpectDeleteUser
       dest: ~/scripts/ExpectDeleteUser
       mode: "0700"

   - name: Start ExpectSetupVPN
     shell: ~/scripts/ExpectSetupVPN {{ openvpn_master_password }}

