---
   - name: Download files from docker.com
     uri:
        url: https://get.docker.com
        return_content: yes
     register: curl_res

   - name: Write curl output to file get-docker.sh
     copy:
       content: "{{ curl_res.content }}"
       dest: /get-docker.sh
       mode: "0777"

   - name: Execute get-docker.sh script
     shell: /get-docker.sh
