---
   - name: Copy datasource for grafana
     copy:
       src: datasources
       dest: ~/configs

   - name: Copy dashboard dir
     copy:
       src: dashboards
       dest: ~/configs

   - name: Copy install_grafana script
     copy:
       src: install_grafana
       dest: ~/configs
       mode: "0700"

   - name: Copy setup_grafana_auth script
     template:
       src: setup_grafana_auth.j2
       dest: ~/configs/setup_grafana_auth
       mode: "0700"

   - name: Install grafana container
     shell: ~/configs/install_grafana

   - name: Wait grafana intializing
     wait_for:
       timeout: 10

   - name: Change password for grafana admin
     shell: ~/configs/setup_grafana_auth

   - name: Removing setup_grafana_auth script
     shell: rm ~/configs/setup_grafana_auth
