---

   - name: Get grafana docker container name
     shell: docker ps -a | grep "/run.sh" | awk '{ print $NF }'
     register: image_name

   - name: Killing container
     shell: docker kill {{ image_name.stdout }}
     ignore_errors: True
     when: image_name.stdout != ""

   - name: Removing container
     shell: docker rm {{ image_name.stdout }}
     when: image_name.stdout != ""


#   - name: Identifying vpn network
#     shell: ifconfig | grep utun -A2 | grep "inet " | awk '{print $2}'
#     register: subnet

   - name: Creating datasource directory
     file: 
       path: ~/configs/datasources 
       state: directory

   - name: Copy datasource for grafana
     template:
       src: datasources/sample.j2
       dest: ~/configs/datasources/sample.yaml

   - name: Copy dashboard dir
     copy:
       src: dashboards
       dest: ~/configs

   - name: Copy install_grafana script
     copy:
       src: install_grafana
       dest: ~/configs
       mode: "0700"

   - name: Copy setup_grafana_auth script
     template:
       src: setup_grafana_auth.j2
       dest: ~/configs/setup_grafana_auth
       mode: "0700"

   - name: Install grafana container
     shell: ~/configs/install_grafana {{ subnet.stdout }}

   - name: Wait grafana intializing
     wait_for:
       timeout: 10

   - name: Change password for grafana admin
     shell: ~/configs/setup_grafana_auth {{ subnet.stdout }}

   - name: Removing setup_grafana_auth script
     shell: rm ~/configs/setup_grafana_auth
