---
   - name: Get prometheus docker container name
     shell: docker ps -a | grep "/bin/prometheus" | awk '{ print $NF }'
     register: image_name

   - name: Killing container
     shell: docker kill {{ image_name.stdout }}
     ignore_errors: True
     when: image_name.stdout != ""

   - name: Removing container
     shell: docker rm {{ image_name.stdout }}
     when: image_name.stdout != ""

   - name: Include configuration vars
     include_vars:
       file: ./variables.yml

   - name: Create /configs directory
     file:
       state: directory
       path: ~/configs

   - name: Copy prometheus configuration file
     template:
       src: prometheus.j2
       dest: ~/configs/prometheus.yml
       mode: "0666"

   - name: Installing OpenVPN client
     apt:
       pkg:
         - openvpn
       state: present

   - name: Copying .ovpn file to /etc/openvpn/server
     copy:
       src: ovpn_users/monitor.ovpn
       dest: /etc/openvpn/client/monitor.conf

   - name: Start openvpn server
     shell: systemctl start openvpn-client@monitor

   - name: Identifying vpn network
     shell: ip address | grep tun0 -A2 | grep "inet " | awk '{print $2}'
     register: subnet

   - name: Install prometheus container
     shell: docker run -d -v ~/configs/prometheus.yml:/etc/prometheus/prometheus.yml -p {{ subnet.stdout }}:9090:9090 prom/prometheus

   - name: Remove configs directory
     shell: rm -r -f ~/configs

   - name: Install grafana
     import_tasks: install_grafana.yml
