---
   - name: Create /configs directory
     file:
       state: directory
       path: ~/configs

   - name: Copy prometheus configuration file
     template:
       src: prometheus.j2
       dest: ~/configs/prometheus.yml

   - name: Install prometheus container
     shell: docker run -d -v ~/configs/prometheus.yml:/etc/prometheus/prometheus.yml -p 127.0.0.1:9090:9090 prom/prometheus

   - name: Install nginx
     import_tasks: nginx_setup.yml

   - name: Install grafana
     import_tasks: install_grafana.yml
