---
   - name: Install nginx and apache2-utils
     apt:
       pkg:
         - nginx
         - apache2-utils
       state: present
       update_cache: yes

   - name: Creating file /etc/nginx/htpasswd
     shell: touch /etc/nginx/htpasswd

   - name: Creating test user
     shell: htpasswd -b /etc/nginx/htpasswd {{ nginx_login }} {{ nginx_passwd }}

   - name: Check if default files exists
     stat:
       path: /etc/nginx/sites-enabled/default
     register: file

   - name: Remove default files
     shell: rm /etc/nginx/sites-available/default & rm /etc/nginx/sites-enabled/default
     when: file.stat.exists

   - name: Copy prometheus file to enabled sites
     copy:
       src: nginx-config/prometheus
       dest: /etc/nginx/sites-enabled

   - name: Copy prometheus file to available sites
     copy:
       src: nginx-config/prometheus
       dest: /etc/nginx/sites-available

   - name: Start nginx server
     shell: systemctl start nginx
