---
   - name: Check if user exists
     command: ls /home/bot
     register: result 
     ignore_errors: True

   - name: User status
     debug:
       msg: "User bot is already created on server!"
     when: result.failed == false

   - name: Create user bot
     user:
       name: bot
       state: present
       shell: /bin/bash
       force: no
     when: result.failed == true

   - name: Add provision user to the sudoers
     copy:
       dest: "/etc/sudoers.d/bot"
       content: "bot  ALL=(ALL)  NOPASSWD: ALL"
     when: result.failed == true


   - name: Deploy ssh key
     authorized_key:
       user: bot
       state: present
       key: "{{ lookup('file', './bot_rsa.pub') }}"
     when: result.failed == true

