    - name: Adding new VPN user
      shell: ~/scripts/ExpectAddUserVPN {{ name }} {{ openvpn_master_password }}
      args:
        chdir: ~/users

    - name: Remove gateway redirection from .ovpn file
      shell: sed -i '/redirect-gateway def1/d' ~/users/{{ name }}.ovpn

    - name: Copying .ovpn file to current pc 'ovpn_users' directory
      fetch:
        src: ~/users/{{ name }}.ovpn
        dest: ./ovpn_users/{{ name }}.ovpn
        flat: yes
